//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTAN.SQLServerDAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTAN.SQLServerDAL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;AdminMenus&gt;
        ///  &lt;MenuItems&gt;
        ///    &lt;MenuItem MenuName=&quot;网站设置&quot; ID=&quot;1&quot; IcoName=&quot;leftico01.png&quot;&gt;
        ///      &lt;ChildItems&gt;
        ///        &lt;ChildItem&gt;
        ///          &lt;ID&gt;1000&lt;/ID&gt;
        ///          &lt;IcoName&gt;/Content/account/config-icon.png&lt;/IcoName&gt;
        ///          &lt;FatherID&gt;1&lt;/FatherID&gt;
        ///          &lt;ActionName&gt;SysConfig&lt;/ActionName&gt;
        ///          &lt;ControllerName&gt;Manage&lt;/ControllerName&gt;
        ///          &lt;MenuName&gt;网站设置&lt;/MenuName&gt;
        ///          &lt;Url&gt;/Manage/SysConfig&lt;/Url&gt;
        ///          &lt;Visible&gt;1&lt;/Visible&gt;
        ///        &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminMenus {
            get {
                return ResourceManager.GetString("AdminMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 前后端通信相关的配置,注释只允许使用多行方式 */
        ///{
        ///    /* 上传图片配置项 */
        ///    &quot;imageActionName&quot;: &quot;uploadimage&quot;, /* 执行上传图片的action名称 */
        ///    &quot;imageFieldName&quot;: &quot;upfile&quot;, /* 提交的图片表单名称 */
        ///    &quot;imageMaxSize&quot;: 2048000, /* 上传大小限制，单位B */
        ///    &quot;imageAllowFiles&quot;: [&quot;.png&quot;, &quot;.jpg&quot;, &quot;.jpeg&quot;, &quot;.gif&quot;, &quot;.bmp&quot;], /* 上传图片格式显示 */
        ///    &quot;imageCompressEnable&quot;: true, /* 是否压缩图片,默认是true */
        ///    &quot;imageCompressBorder&quot;: 1600, /* 图片压缩最长边限制 */
        ///    &quot;imageInsertAlign&quot;: &quot;none&quot;, /* 插入的图片浮动方式 */
        ///    &quot;imageUrlPrefix&quot;: &quot;&quot;, /* 图片访问路径前缀 */
        ///    &quot;imagePathFormat&quot;: &quot;u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditorConfig {
            get {
                return ResourceManager.GetString("EditorConfig", resourceCulture);
            }
        }
    }
}
